/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Ana
 */
public class frmPaginaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPaginaPrincipal
     */
    public frmPaginaPrincipal(String idUsuario, String nomUsuario, String tipo) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        setTitle("Página principal");
        lblIdUsuario.setText(idUsuario);
        lblNombreUsuario.setText(nomUsuario);
        lblTipoUsuario.setText(tipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblTipoUsuario = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        lblIdUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnSalir = new javax.swing.JMenu();
        btnRegistro = new javax.swing.JMenu();
        btnCiudadanos = new javax.swing.JMenuItem();
        btnInstituciones = new javax.swing.JMenuItem();
        btnMantenimiento = new javax.swing.JMenu();
        btnReporteAverias = new javax.swing.JMenuItem();
        btnListadoAverias = new javax.swing.JMenuItem();
        btnSeguimientoAverias = new javax.swing.JMenuItem();
        btnInversionConceptoAverias = new javax.swing.JMenuItem();
        btnAcerca = new javax.swing.JMenu();
        btnCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTipoUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTipoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblTipoUsuario.setText("Tipo de Usuario");

        lblNombreUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsuario.setText("Nombre de Usuario");

        lblIdUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblIdUsuario.setText("ID de Usuario");

        jDesktopPane1.setLayer(lblTipoUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblNombreUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblIdUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdUsuario)
                    .addComponent(lblNombreUsuario)
                    .addComponent(lblTipoUsuario))
                .addContainerGap(676, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIdUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblNombreUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblTipoUsuario)
                .addContainerGap(390, Short.MAX_VALUE))
        );

        btnSalir.setText("Salir");
        jMenuBar1.add(btnSalir);

        btnRegistro.setText("Registro");

        btnCiudadanos.setText("Registro de ciudadanos");
        btnRegistro.add(btnCiudadanos);

        btnInstituciones.setText("Registro de instituciones");
        btnRegistro.add(btnInstituciones);

        jMenuBar1.add(btnRegistro);

        btnMantenimiento.setText("Mantenimiento");

        btnReporteAverias.setText("Reporte de averías");
        btnReporteAverias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteAveriasActionPerformed(evt);
            }
        });
        btnMantenimiento.add(btnReporteAverias);

        btnListadoAverias.setText("Listado de averías");
        btnMantenimiento.add(btnListadoAverias);

        btnSeguimientoAverias.setText("Seguimiento de averías");
        btnMantenimiento.add(btnSeguimientoAverias);

        btnInversionConceptoAverias.setText("Inversión por concepto de averías");
        btnMantenimiento.add(btnInversionConceptoAverias);

        jMenuBar1.add(btnMantenimiento);

        btnAcerca.setText("Acerca de.");

        btnCreditos.setText("Créditos");
        btnAcerca.add(btnCreditos);

        jMenuBar1.add(btnAcerca);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteAveriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteAveriasActionPerformed
        frmReporteAverias obj = new frmReporteAverias();
        jDesktopPane1.add(obj);       
        obj.toFront();
        obj.setLocation(jDesktopPane1.getWidth() / 2 - obj.getWidth() / 2, jDesktopPane1.getHeight() / 2 - obj.getHeight() / 2);
        obj.setVisible(true);
    }//GEN-LAST:event_btnReporteAveriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPaginaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new frmPaginaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnAcerca;
    private javax.swing.JMenuItem btnCiudadanos;
    private javax.swing.JMenuItem btnCreditos;
    private javax.swing.JMenuItem btnInstituciones;
    private javax.swing.JMenuItem btnInversionConceptoAverias;
    private javax.swing.JMenuItem btnListadoAverias;
    private javax.swing.JMenu btnMantenimiento;
    private javax.swing.JMenu btnRegistro;
    private javax.swing.JMenuItem btnReporteAverias;
    private javax.swing.JMenu btnSalir;
    private javax.swing.JMenuItem btnSeguimientoAverias;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    public static javax.swing.JLabel lblIdUsuario;
    public static javax.swing.JLabel lblNombreUsuario;
    public static javax.swing.JLabel lblTipoUsuario;
    // End of variables declaration//GEN-END:variables
}
